github:
    name:           hiqdev/minii-caching

package:
    type:           library
    name:           caching
    namespace:      yii\caching
    title:          minii Caching
    keywords:       minii, caching
    description:    |
        [minii](https://github.com/hiqdev/minii-core) is mini version of [Yii2](http://yiiframework.com/), supposed to be fully compatible.
        This package provides yii\caching.

require:
    minii/hidev-vendor: "*"
    hiqdev/hidev-php:   "*"
