package:
    type:           library
    name:           minii-caching
    namespace:      yii\caching
    title:          minii Caching
    keywords:       minii, caching
    description:    |
        [minii](https://github.com/hiqdev/minii-core) is mini version of [Yii2](http://yiiframework.com/), supposed to be fully compatible.
        This package provides caching.

composer.json:
    name:           minii/caching

require:
    hiqdev/hidev-hiqdev: "*"
    hiqdev/hidev-php:    "*"
