github:
    full_name:      hiqdev/minii-caching

package:
    type:           yii2-extension
    name:           caching
    title:          minii Caching
    keywords:       minii, caching
    namespace:      yii\caching
    description:    |
        [minii](https://github.com/hiqdev/minii-core) is mini version of [Yii2](http://yiiframework.com/), supposed to be fully compatible.

        This package provides `yii\caching`.

require:
    hiqdev/hidev-php:   "*"
    minii/hidev-vendor: "*"
